apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tall-grouse-nodejs 
  janus-idp.io/tekton: tall-grouse-nodejs
  backstage.io/kubernetes-id: tall-grouse-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: tall-grouse-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  